name       : perl-business-isbn-data
version    : '20191107'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-Data-20191107.tar.gz : 844c4f64f193d389340b4465a1d5bc34c60f0c8e42e5c69ac8afe3d3bbc5ca0d
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN::Data - data pack for Business::ISBN
description: |
    Business::ISBN::Data - data pack for Business::ISBN
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
