name       : perl-business-isbn-data
version    : '20230719.001'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-Data-20230719.001.tar.gz : 69d7eec7be1cf459dd8240d8097bfd3cde4091366bb1a78a876b46cde7d228a6
homepage   : https://metacpan.org/pod/Business::ISBN::Data
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN::Data - data pack for Business::ISBN
description: |
    Business::ISBN::Data - data pack for Business::ISBN
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
