name       : perl-business-isbn-data
version    : '20210112.006'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-Data-20210112.006.tar.gz : 98c2cfb266b5fdd016989abaa471d9dd4c1d593c508a6f01f66d184d5fee8bae
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN::Data - data pack for Business::ISBN
description: |
    Business::ISBN::Data - data pack for Business::ISBN
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
